# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.3.x"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.3.x"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.3.x"
    open-pull-requests-limit: 0

  - package-ecosystem: "uv" # See documentation for possible values
    directory: "./test/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.3.x"
    pull-request-branch-name:
      template: "deps/semver1.3.x/{package_manager}-{dependency}-{version}"
      separator: "/"
      word-separator: "_"
      branch-name-case: "lowercase"
      max-length: 100
    
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"
    target-branch: "docs"
    pull-request-branch-name:
      template: "deps/semver1.3.x/{package_manager}-{dependency}-{version}"
      separator: "/"
      word-separator: "_"
      branch-name-case: "lowercase"
      max-length: 100
    
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "docs"
    pull-request-branch-name:
      template: "deps/semver1.3.x/{package_manager}-{dependency}-{version}"
      separator: "/"
      word-separator: "_"
      branch-name-case: "lowercase"
      max-length: 100
    
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "docs"
    pull-request-branch-name:
      template: "deps/semver1.3.x/{package_manager}-{dependency}-{version}"
      separator: "/"
      word-separator: "_"
      branch-name-case: "lowercase"
      max-length: 100

  # Legacy
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.2.x"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.2.x"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "semver1.2.x"
    open-pull-requests-limit: 0
