[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "key-multivalue-storage"
version = "v1.3.0.20260608a3"
description = "A simple library that allows the JSON storage of one key to multiple values."
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-2.0-only"
license-files = ["LICENSE"]
authors = [{name = "Boss_1s"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Database",
    "Topic :: File Formats :: JSON",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
keywords = [
    "json",
    "json wrapper",
    "python",
    "database",
    "storage",
    "wrapper-library"
]

[project.optional-dependencies]
dev = ["pylint"]

[project.urls]
Documentation = "https://github.com/Boss-1s/key_multivalue_storage/wiki/"
Repository = "https://github.com/Boss-1s/key_multivalue_storage/"
Issues = "https://github.com/Boss-1s/key_multivalue_storage/issues/"

# TODO in v2.0: CLI
#[project.scripts]
#command = "kms:func"...
#...
