sonar.projectKey=Boss-1s_key_multivalue_storage
sonar.organization=boss-1s


sonar.projectName=key_multivalue_storage
sonar.projectVersion=v1.3.2.20260826b1


sonar.sources=src/key_multivalue_storage

sonar.sourceEncoding=UTF-8

sonar.tests=test

sonar.verbose=true

sonar.python.versions=3.12,3.13,3.14


sonar.python.pylint.reportPaths=pylint-report.json
sonar.python.coverage.reportPaths=coverage.xml