name: Feature Request
title: "feat: "
description: Request a feature and/or enhancement.
labels: ["enhancement", "Needs Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your ideas! Please be sure to read through our [Contribution Guideline](https://github.com/Boss-1s/key_multivalue_storage/blob/main/docs/CONTRIBUTING.md), there are some very important things that you must read before continuing. Thanks!
  - type: textarea
    id: desc
    attributes:
      label: "What's the feature?"
      description: "Describe the feature. What's it like? What will it do?"
    validations:
      required: true
  - type: textarea
    id: prob
    attributes:
      label: "What problem does it solve?"
      description: "Describe the problem that this feature will solve. How will it encourage better usage of the library? How will it keep things running smoothly?"
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Possible Code
      description: "If possible, provide a Python mockup of the feature. It dosen't have to be synatically correct; just clear enough to understand how it works."
      render: python
  - type: dropdown
    id: ver
    attributes:
      label: Expected Version
      description: "What version would you like this feature to come out in? If a feature contains small breaking changes, please choose the next minor version. If it contains large-scale breaking changes, please choose the next major version. [See more about versioning here](https://github.com/Boss-1s/key_multivalue_storage/blob/main/docs/SECURITY.md#pypi-versioning)"
      options: [
        ">kms-v1.2.3...",
        ">=kms-v1.3.x...",
        ">=kms-v1.4.x...",
        ">=kms-v1.5.x...",
        ">=kms-v1.6.x...",
        ">=kms-v2.0.x...",
        ">=kms-v2.1.x..."
      ]
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisite Checks
      description: Please make sure you have done the following, and check them off as follows. This is necessary to prevent duplicate requests or unreleated features from being suggested here. Thanks!
      options:
        - label: I have checked the roadmap and have ensured that the feature I am requesting is not a planned feature already.
          required: true
        - label: I have checked other issues and have ensured that this is not a duplicate, and has not been suggested before.
          required: true
        - label: I am requesting this feature on behalf of a supported version of kms (kms-semver1.2.0 and later).
          required: true
        - label: "**I request that my feature, if accepted, not be shown on the roadmap.** (All accepted features will be added to the roadmap by default.)"
          required: false
