"""
Key to Multivalue Storage - 'storage' Module

This module contains the 'Storage' class. This is the
main class in which this library is centralized about.
You can create instances of this class using the format
`Storage(key, subkey=subvalue...)` and storing it in a
JSON file with `.store(file_path)`.

Made with love by Boss_1s.
(c)2025, 2026. This work is released under the GPL General License v2.0.
"""
# pylint: skip-file
from __future__ import annotations

from collections.abc import KeysView
import uuid
from functools import total_ordering
from types import TracebackType
from typing import Any, Callable, Generator, overload
from typing_extensions import deprecated

from .utils import metadata as meta

# Top-level functions
def help() -> None: ...
def print(*args: Any, **kwargs: Any) -> None: ...

@total_ordering
# 🎯 Inheriting from dict[Any, Any] provides complete structural freedom!
# This clears your assignment errors while welcoming your custom overloads naturally.
class Storage[TopKey = str, SubKey = str, SubVal = Any](dict[Any, Any],metaclass=meta._StorageMeta):
    # Global attributes
    indent: int
    encode: bool
    auto_delete_self: bool

    # Instance attributes (Explicitly tracks your strict 3-slot types)
    instance_id: uuid.UUID
    key: TopKey
    values: dict[Any, Any] # pyright: ignore[reportIncompatibleMethodOverride]

    _default_valueerror_msg: str

    def __init__(self, key: TopKey, **kwargs: SubVal) -> None: ...
    def __init_subclass__(cls, **kwargs: Any) -> None: ...

    @staticmethod
    def _encode(string: Any) -> int: ...
    @staticmethod
    def _decode(string: str | int) -> str: ...

    def _to_dict(self, encode: bool = False) -> dict[TopKey, dict[SubKey, SubVal]]: ...

    @classmethod
    @deprecated("This private method will be removed soon.")
    def _from_dict(cls, data_dict: dict[TopKey, dict[SubKey, SubVal]], raw: bool = False) -> Storage[TopKey, SubKey, SubVal]: ...

    @classmethod
    def help(cls, method: Callable[..., Any] | None = None) -> None: ...

    def store(self, file_path: str, instant_delete: bool | None = None, indent: int | None = None, encode: bool | None = None) -> None: ...

    def to_dict(self) -> dict[str, dict[str, Any]]: ...
    def keys(self) -> KeysView[Any]: ... #type: ignore

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...

    def __add__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal] | list[Any]) -> Storage[TopKey, SubKey, SubVal]: ...
    def __radd__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal]: ...
    def __sub__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal]: ...
    def __rsub__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal]: ...
    @overload
    def __truediv__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal]: ...
    @overload
    def __truediv__(self, other: int) -> list[Storage[TopKey, SubKey, SubVal]]:...
    def __rtruediv__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal]: ...

    #FIXME: needs overloads
    def __and__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal] | int: ...
    def __or__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal] | int: ... # pyright: ignore[reportIncompatibleMethodOverride]
    def __xor__(self, other: Storage[TopKey, SubKey, SubVal] | dict[SubKey, SubVal]) -> Storage[TopKey, SubKey, SubVal] | int: ...
    def __lshift__(self, other: int) -> Storage[TopKey, SubKey, SubVal] | int: ...
    def __rshift__(self, other: int) -> Storage[TopKey, SubKey, SubVal] | int: ...

    @overload
    def __getitem__(self, key: TopKey) -> dict[SubKey, SubVal]: ...
    @overload
    def __getitem__(self, key: SubKey) -> SubVal: ...
    @overload
    def __getitem__(self, key: int) -> SubVal: ...
    @overload
    def __getitem__(self, key: slice) -> list[SubVal]: ...

    @overload
    def __setitem__(self, key: SubKey, value: SubVal) -> None: ...
    @overload
    def __setitem__(self, key: int, value: SubVal) -> None: ...

    def __delitem__(self, key: SubKey | int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: Any) -> bool: ...

    def __iter__(self) -> Generator[TopKey | dict[SubKey, SubVal], None, None]: ... # NOSONAR

    def __getattr__(self, name: Any) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __call__(self, **kwargs: SubVal) -> None: ...
    def __enter__(self) -> dict[SubKey, SubVal]: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...
    def __format__(self, format_spec: str) -> str: ...
