# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"

group :jekyll_plugins do
  gem "jekyll-gfm-admonitions"
  gem "jekyll-remote-theme"
  gem "jekyll-optional-front-matter"
  gem "jekyll-seo-tag"
  gem 'jekyll-env'
end
