# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-gfm-admonitions"
  gem "jekyll-remote-theme"
  gem "jekyll-optional-front-matter"
  gem "jekyll-seo-tag"
  gem "jekyll-sticky-toc"
end
