# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-gfm-admonitions", git: "https://github.com/Boss-1s/jekyll-gfm-admonitions/", branch: "patch-1"
  gem "jekyll-remote-theme"
  gem "jekyll-optional-front-matter"
  gem "jekyll-seo-tag"
end
