name: Backporter / Forward Porter

on:
  pull_request:
    types: ["labeled", "closed"] # IMPORTANT: FOR TESTING ONLY
  pull_request_target:
    types: ["labeled", "closed"]
  push:
    branches-ignore:
      - "eol/**"
      - "release/**"
      - "docs"

jobs:
    comment:
      if: github.event.action == 'labeled'
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
        - name: Check if backport label is present in PR
          run: |
            if [[ ${{ contains(github.event.pull_request.labels.*.name, 'backport-to-') }} ]]; then
              echo "Backport label is present; commenting on the PR."
              echo "backport_label_present=true" >> $GITHUB_ENV
            else
              echo "Backport label is not present. Ending job."
              echo "backport_label_present=false" >> $GITHUB_ENV
            fi
        - name: Comment
          uses: peter-evans/create-or-update-comment@34c8c3685e6cc7ac706e04c83308164410d8976f
          if: env.backport_label_present == 'true'
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              This PR has been labeled for backporting. The backport process will be executed once the PR is merged. Thank you for contributing to kms!
    backport-pr:
      if: github.event.pull_request.merged == true && !(contains(github.event.pull_request.labels.*.name, 'backport'))
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
        - name: Backport Action
          uses: sorenlouv/backport-github-action@f98adcdb38c8a19480f3d6abefbbace9eecaf009
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              auto_backport_label_prefix: backport-to-

        - name: Info log
          if: ${{ success() }}
          run: cat ~/.backport/backport.info.log

        - name: Debug log
          if: ${{ failure() }}
          run: cat ~/.backport/backport.debug.log
    backport-commit:
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v7.0.1
        - name: Extract Prefix from Commit
          id: prefix
          uses: somaz94/commit-info-extractor@v1
          with:
            commit_limit: 1
            extract_pattern: "(?i)\\[backport\\s+([^\\]]+)\\]"
            pretty: true
        - name: Setup node.js
          if: steps.prefix.outputs.value_variable
          uses: actions/setup-node@v6.5.0
        - name: Backport latest commit (if possible)
          if: steps.prefix.outputs.value_variable
          run: |
            npx backport -b ${{ steps.prefix.outputs.value_variable }} --non-interactive --sha ${{ github.event.after }}
            
