# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: pages build and deployment

on:
  push:
    branches: ["docs"]
    paths:
      - "docs/*"
      - "*/_config.yml"
      - ".github/workflows/jekyll-gh-pages.yml"
  gollum:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  retrigger:
    if: github.ref_name != 'docs'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: docs
      - env:
          GH_TOKEN: ${{github.token}}
        run: gh workflow run .github/workflows/jekyll-gh-pages.yml --ref docs
