name: Regenerate Changelog (trigger)

on:
  release:
    types: [edited, published]

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v7
        with:
          ref: docs
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run .github/workflows/regenerate.yml --ref docs

