name: Regenerate Changelog

on:
    workflow_dispatch:
    release:
        types: [edited]

jobs:
    generate:
        if: github.event.release.draft == false
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install SSH Key
              uses: webfactory/ssh-agent@v0.10.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: Setup SSH and signing
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: bash .github/workflows/src/ssh.sh

            - name: Set up Python
              uses: actions/setup-python@v4

            - name: Set up UV
              uses: astral-sh/setup-uv@v7
              with:
                enable-cache: true

            - name: Install dependencies
              run: |
                  uv sync --only-group release

            - name: (Re)Generate Changelog
              env:
                GITHUB_TOKEN: ${{ github.token }}
              run: |
                uv run python test/automation/changelog_generate.py
            
            - name: Commit and Push Changes
              env:
                REF: "main"
                DUMMY: "false"
                REPO: ${{ github.repository }}
                CUSTOM_COMMIT_MSG: "changelog regenerated"
              run: |
                git checkout -B "$REF" "origin/$REF"
                bash .github/workflows/src/push.sh
