name: Release
description: Workflow for official releases to PyPi, run when a release is created on GitHub.

on:
  workflow_dispatch: 
  release:
    types: [published]

jobs:
  deploy:
    environment: "release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Automatically Update Version
        env:
          NVERSION: ${{ github.event.release.tag_name }}
          RELEASENVERSION: ${{ github.event.release.name }}
        run: python3 .github/workflows/src/release.py

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build Package
        run: python -m build # Generates the dist/ files

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # Official PyPI upload action

      - name: Commit version change
        env:
          REF: ${{ github.event.release.name }}
        run: |
          # Get the branch name and strip the 'origin/' prefix
          export BRANCH=$(git branch --contains ${{github.ref_name}})
          echo "$REF is sourced from branch: $BRANCH"
          git config --global user.name 'Boss_1s [via Actions]'
          git config --global user.email 'Boss-1s[auto]@users.noreply.github.com'
          bash .github/workflows/src/push.sh

      - name: Rename files for GH release upload
        run: |
          cd dist
          for file in *; do
            new_name=$(echo "$file" | sed 's/key_multivalue_storage/kms_package/')
            mv "$file" "$new_name"
          done
          cd ..

      - name: Upload Build to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/*
