name: Release
description: Workflow for official releases to PyPi, run when a release is created on GitHub.

on:
  workflow_dispatch: 
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "release"
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - name: Setup SSH and signing
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: bash .github/workflows/src/ssh.sh
        
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Setup SSH and signing
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: bash .github/workflows/src/ssh.sh
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Automatically Update Version
        env:
          NVERSION: ${{ github.event.release.tag_name }}
          RELEASENVERSION: ${{ github.event.release.name }}
        run: python3 .github/workflows/src/release.py

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build Package
        run: python -m build # Generates the dist/ files

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Commit version change
        continue-on-error: true
        env:
          REF: "kms-v1.2.3/2026.05.23"
          DUMMY: "true"
          TARGET_BRANCH: "${{ github.event.release.target_committish }}"
          REF_BRANCH: ${{ github.ref_name }}
        run: |
          # 1. Safely evaluate environment variables without syntax parsing flaws
          if [ -n "$TARGET_BRANCH" ]; then
            export BRANCH="$TARGET_BRANCH"
          else
            export BRANCH="$REF_BRANCH"
          fi
          
          echo "$REF is sourced from branch: $BRANCH"
          
          # 2. Realign HEAD onto the tracking stream 
          git checkout -B "$BRANCH" "origin/$BRANCH"
          
          bash .github/workflows/src/push.sh

      - name: Rename files for GH release upload
        run: |
          cd dist || exit 1
          for file in *; do
            new_name=$(echo "$file" | sed 's/key_multivalue_storage/kms_package/')
            mv "$file" "$new_name"
          done
          cd ..

      - name: Upload Build to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/*
