name: Tests

on:
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        py-ver: ['3.12', '3.13', '3.14']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py-ver }}
        # --- ULTRA FAST WINDOWS TESTING (NO PYTEST) ---
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        if: ${{ runner.os == 'Windows' }}
        with:
         enable-cache: true

      - name: Run Python Tests
        if: ${{ runner.os == 'Windows' }}
        run: uv run --with . python test/test-general.py
      
      - name: Install Self
        if: ${{ runner.os != 'Windows' }}
        run: python -m pip install -e .
        
      - name: Run test file
        if: ${{ runner.os != 'Windows' }}
        run: python3 test/test-general.py

      - name: Install and run pyproject.toml lint (uv)
        if: ${{ runner.os == 'Windows' }}
        id: uv-toml
        continue-on-error: true
        run: uvx pyproject check

      - name: Install and run pyproject.toml lint (pip)
        if: ${{ runner.os != 'Windows' }}
        id: pip-toml
        continue-on-error: true
        run: pip install pyproject && pyproject check

      - name: Lint YAML Files
        id: yml
        if: ${{ runner.os == 'Linux' }}
        continue-on-error: true
        uses: reviewdog/action-actionlint@v1.72.0
        with:
          actionlint_flags: '-color -oneline'
          level: info
          fail_level: error

      - name: Lint Bash Files
        id: sh
        if: ${{ runner.os != 'Windows' }}
        continue-on-error: true
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          format: gcc
          severity: error

      - name: Fail job if steps failed
        if: ${{ steps.pip-toml.outcome == 'failure' || steps.uv-toml.outcome == 'failure' || steps.yml.outcome == 'failure' || steps.sh.outcome == 'failure' }}
        run: |
          echo ::error Failed!:: A step may have failed, skipping deployment and failing job.
          exit 1
          
  deploy-to-test:
    needs: build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: test
    if: |
      github.ref_name == 'main' ||
      (github.actor == 'dependabot[bot]' && contains(github.ref_name, 'main'))
    steps:
      - run: |
          echo all jobs successful 
          echo deploying to environment test

  deploy-to-beta:
    needs: build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: beta
    if: |
      github.ref_name == 'beta' ||
      (github.actor == 'dependabot[bot]' && contains(github.ref_name, 'beta'))
    steps:
      - run: |
          echo all jobs successful 
          echo deploying to environment beta
          
