name: Tests

on:
  push:
    branches-ignore:
      - releases/**
      - eol/**
      - docs
  pull_request:
    branches-ignore:
      - releases/**
      - eol/**
      - docs
  workflow_dispatch:

jobs:
  main:
    environment: test
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        py-ver: ['3.12', '3.13', '3.14']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # Setup
      - parallel:
        - name: Setup Python
          uses: actions/setup-python@v7
          with:
            python-version: ${{ matrix.py-ver }}

        - name: Set up uv
          uses: astral-sh/setup-uv@v9.0.0
          with:
           enable-cache: true

      - name: Install and Ensure Dependecies
        run: |
          uv sync --group test
          uv run coverage --version
          uv run shellcheck --version
          uv run pylint --version
          uv run pyproject --version

      - name: Run Python Tests
        id: self-tests
        background: true
        if: ${{ runner.os != 'Windows' }}
        run: |
          uv run coverage run -m test
          uv run coverage report
          uv run coverage xml

      - name: Run Python Tests (Windows)
        id: self-tests-w
        background: true
        if: ${{ runner.os == 'Windows' }}
        env:
          TERM: 'dumb'
          PYTHONUTF8: '1'
        run: |
          uv run coverage run -m test
          uv run coverage report
          uv run coverage xml

      - name: Lint using Pylint
        background: true
        id: pylint
        run: pylint --output-format=json:pylint-report.json,colorized --recursive=y key_multivalue_storage test/ .github/workflows/src/

      - name: Lint pyproject.toml
        id: toml
        background: true
        run: pyproject check

      - name: Lint YAML Files
        id: yml
        background: true
        if: ${{ runner.os == 'Linux' }}
        uses: reviewdog/action-actionlint@a499b807aed4af40b8f2f7b885b9e38c469a945c
        with:
          actionlint_flags: '-color -oneline'
          level: info
          fail_level: error

      - name: Lint Bash Files
        id: sh
        background: true
        if: ${{ runner.os != 'Windows' }}
        run: |
          uv run shellcheck --version
          echo ""
          find . -path './.venv' -prune -o -name '*.sh' -exec uv run shellcheck --severity=error {} +

      - name: Wait for Pylint and Coverage
        wait: [pylint, self-tests, self-tests-w]

      - name: Analyze with SonarCloud
        id: sc-analyze
        uses: SonarSource/sonarqube-scan-action@ad8210318ac8bb816e41990d5af2b304f7a6c213
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=Boss-1s_key_multivalue_storage
            -Dsonar.organization=boss-1s
            -Dsonar.projectName=key_multivalue_storage
            -Dsonar.projectVersion=1.3.0.20260731
            -Dsonar.sources=src/key_multivalue_storage
            -Dsonar.tests=test
            -Dsonar.verbose=true
            -Dsonar.python.versions=3.12,3.13,3.14
            -Dsonar.python.pylint.reportPaths=pylint-report.json
            -Dsonar.python.coverage.reportPaths=coverage.xml
          projectBaseDir: .

      - name: SonarQube Quality Gate check
        id: sc-qg
        uses: sonarsource/sonarqube-quality-gate-action@8e9b0ca0a7273d6f16986388d98393efdfcf56fd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Export Sonar Issues to SARIF File
        id: sc-sarif
        uses: vmvarela/sonarqube-sarif@ee6c3c1d5314dd0d402277cd5099ab4578ddca74
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          # For SonarCloud, use your project key you just set up in that popup box
          project-key: "Boss-1s_key_multivalue_storage"
          # Default SonarCloud API URL
          sonar-host-url: "https://sonarcloud.io"

      - name: Upload Code Scanning Results
        id: sc-upload
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'sonarqube.sarif'

      - wait-all:

  codeql:
    uses: ./.github/workflows/codeql.yml
    if: always()


  nightly:
    needs: [main, codeql]
    uses: ./.github/workflows/release-nightly.yml
    if: |
      github.ref_name == 'semver1.3.x' ||
      contains(github.actor, 'renovate') ||
      contains(github.actor, 'dependabot') ||
      contains(github.actor, 'github-actions')
