name: Tests

on:
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        py-ver: ['3.12', '3.13', '3.14']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py-ver }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
         enable-cache: true

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          uv sync

      - name: Run Python Tests
        run: uv run --with . python test/test-general.py

      - name: Display Breaking Changes (beta)
        if: ${{ github.ref_name == 'beta' }}
        env:
          OLDTAG: 'v1.2.3.20260523.1'
        run: uv run --with .[dev] python test/diff.py
      
      - name: Lint using Pylint
        continue-on-error: true
        id: pylint
        run: |
          uv run pylint --recursive=y key_multivalue_storage test/ .github/workflows/src/
      
      - name: Lint pyproject.toml
        id: toml
        continue-on-error: true
        run: uv run pyproject check

      - name: Lint YAML Files
        id: yml
        if: ${{ runner.os == 'Linux' }}
        continue-on-error: true
        uses: reviewdog/action-actionlint@v1.72.0
        with:
          actionlint_flags: '-color -oneline'
          level: info
          fail_level: error

      - name: Lint Bash Files
        id: sh
        if: ${{ runner.os != 'Windows' }}
        continue-on-error: true
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          format: gcc
          severity: error

      - name: Fail job if steps failed
        if: ${{ steps.pylint.outcome == 'failure' || steps.toml.outcome == 'failure' || steps.yml.outcome == 'failure' || steps.sh.outcome == 'failure' }}
        run: |
          echo ::error Failed!:: A step may have failed, skipping deployment and failing job.
          exit 1

  nightly-main:
    needs: build
    permissions: write-all
    uses: ./.github/workflows/release-nightly.yaml

  nightly-beta:
    needs: build
    permissions: write-all
    uses: ./.github/workflows/release-beta-nightly.yml

        
  deploy-to-test:
    needs: nightly-main
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: test
    if: |
      github.ref_name == 'main' ||
      (github.actor == 'dependabot[bot]' && contains(github.ref_name, 'main'))
    steps:
      - run: |
          echo all jobs successful
          echo deploying to environment test

  deploy-to-beta:
    needs: nightly-beta
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: beta
    if: |
      github.ref_name == 'beta' ||
      (github.actor == 'dependabot[bot]' && contains(github.ref_name, 'beta'))
    steps:
      - run: |
          echo all jobs successful
          echo deploying to environment beta

